--<ScriptOptions statementTerminator=";"/>

CREATE TABLE book (
	ID INTEGER UNSIGNED NOT NULL,
	U_ID VARCHAR(64),
	BOOK_NAME VARCHAR(64) NOT NULL,
	PUBLISHER VARCHAR(45) NOT NULL,
	AUTHOR VARCHAR(45) NOT NULL,
	Summary VARCHAR(2000),
	PRIMARY KEY (ID)
);

CREATE TABLE student (
	ID INTEGER UNSIGNED NOT NULL,
	FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR(45) NOT NULL,
	FATHER_NAME VARCHAR(45) NOT NULL,
	GENDER VARCHAR(45) NOT NULL,
	EMAIL VARCHAR(45) NOT NULL,
	MOBILE BIGINT UNSIGNED NOT NULL,
	STUDENT_NUMBER VARCHAR(45) NOT NULL,
	ADMISSION_YEAR INTEGER UNSIGNED NOT NULL,
	ENROLL_NUMBER VARCHAR(45),
	U_ID VARCHAR(64),
	PASSWORD VARCHAR(128) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE operator (
	id INTEGER UNSIGNED NOT NULL,
	user_id VARCHAR(45) NOT NULL,
	password VARCHAR(128) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE issue_book (
	ID INTEGER UNSIGNED NOT NULL,
	STUDENT_ID VARCHAR(64),
	BOOK_ID VARCHAR(64),
	ISSUE_DATE DATE NOT NULL,
	RECEIVE_DATE DATE,
	PRIMARY KEY (ID)
);

